#!/bin/bash

#read gets input from user
#-p means prompt with string
read -p "What is your name? " name
echo "Name is $name"

read -p "How old are you? " age

#spaces are important
if [ $age -ge 16 ]
then
	echo "You can drive"
elif [ $age -eq 15 ]
then
	echo "You can drive next year"
else
	echo "You can't drive"
fi

#
read -p "Enter a number: " num

if ((num == 10)); #can also use [ -eq -ge -le -ne -lt -gt ]
then
	echo "Your number equals 10"
fi

if ((num > 10));
then
	echo "It is greater than 10"
else
	echo "It is less than 10"
fi

if (( ((num % 2)) == 0)); 
then
	echo "It is even"
fi

if (( ((num > 0)) && ((num < 11)) ));
then
	echo "Num is between one and 10"
fi

touch samp_file && vim samp_file

[ -d samp_dir ] || mkdir samp_dir


