// generated by Fast Light User Interface Designer (fluid) version 1.0304

#ifndef hello_h
#define hello_h
#include <FL/Fl.H>
void Button_CB(Fl_Widget *, void *);
void WinQuit_CB(Fl_Widget *, void *);
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Button.H>
#endif
