// generated by Fast Light User Interface Designer (fluid) version 1.0304

#include "hello.h"
#include <stdio.h>
#include <stdlib.h>

void Button_CB(Fl_Widget *, void *) {
  printf("CALLBACK!\n");
}

void WinQuit_CB(Fl_Widget *, void *) {
  printf("Window Quit CALLBACK!\n");
  exit(0);
}

int main(int argc, char **argv) {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(955, 230);
    w = o; if (w) {/* empty */}
    o->callback((Fl_Callback*)WinQuit_CB);
    { Fl_Button* o = new Fl_Button(20, 5, 935, 60, "button");
      o->callback((Fl_Callback*)Button_CB);
    } // Fl_Button* o
    { new Fl_Button(20, 75, 940, 40, "Button2");
    } // Fl_Button* o
    o->end();
  } // Fl_Double_Window* o
  w->show(argc, argv);
  return Fl::run();
}
